export { default as Actor } from './Actor/actor';
export { default as Censor } from './Censor/censor';
export { default as Genre } from './Genre/genre';
export { default as Home } from './Home/home';
export { default as Manager } from './Manager/manager';
export { default as Review } from './Review/review';
export { default as UserInfor } from './UserInfor/userInfor';
export { default as Login } from './Login/login';
export { default as Register } from './Register/register';
export {default as FilmDetails} from './FilmDetails/filmDetails';
export {default as MoreFilm} from './MoreFilm/moreFilm';
