GET http://localhost:5000/api/account
Authorization: x-access-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyaXRodWMiLCJpYXQiOjE2NDgzOTU2MzIsImV4cCI6MTY0ODM5NTY2Mn0.24cq2OhumUouyDFR9qTnymmja6vOdWVTGMdEDIEJJ1M

###
POST http://localhost:5500/auth/refreshToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyaXRodWMiLCJpYXQiOjE2NDgzOTQ2ODV9.8kRIAVKxcW07m69vj6mpJaMHVSdkXUjTlYPUhEXK9Vo"
}

###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
    "email": "trithuc",
    "password": "123456"
}
