GET http://localhost:5000/api/account
Authorization: x-access-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDg0NTcyNzUsImV4cCI6MTY0ODQ1NzMwNX0.bQcXvp9at7Ox6DYISUqlIsrLL4w4OiLr9qVGMLRVdFI

###
POST http://localhost:5500/auth/refreshToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyaXRodWMiLCJpYXQiOjE2NDg0NTcxMjB9.rSCz3e1ANCmxrp1JdGtn8LFjc6_Ff2nFutKaM3TyR1Q"
}

###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
    "email": "trithuc",
    "password": "123456"
}
