GET http://localhost:5500/api/account
//Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRyaXRodWMiLCJpYXQiOjE2NDc5NDkxNzUsImV4cCI6MTY0Nzk0OTIwNX0.7wgyrZ2sGNfsX-xsHkqY1BWHjofWzK5B2l6sltoundM

###
POST http://localhost:5500/auth/refreshToken
Content-Type: application/json

###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
    "email": "trithuc",
    "password": "123456"
}