export { default as Navbar } from './NavBar/navBar';
export { default as Slider } from './Slider/slider'
export { default as MainNavBar } from './MainNavBar/mainNavBar'
export { default as FilmSlider } from './FilmSlider/filmSlider'
export { default as ShowTimeManager } from './ShowTimeManager/showTimeManager'
export { default as Statistics } from './Statistics/statistics'
export { default as TheaterManager } from './TheaterManager/theaterManager'
export { default as Footer } from './Footer/footer';
export { default as Message } from './Message/message'
export { default as BookingForm } from './Booking/BookingForm/bookingForm'
export { default as TypingAnim } from './TypingAnim/typing'